# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48c02eab631935a15095275085ecc8457d157e9961eda64eda4b3dcfbd49c8567717ed82702a5fb899507bb42c4d6b1d17e58a092b5da2464fa05284c8da443f

test:
  secret_key_base: 14088051244d8a7cced6fd359ebce2be1297b3ba4135febcf1f5c95d33d6fb4444956e920f00a79daa0d3ba4f60f97fc1f190006262c3327cb48bfb6ed5d92dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
